### ISSUE TITLE
AAU, I want to be able to choose which stock data is displayed on the scrollable widget view

### ISSUE THREAD

**Issue by andypham29** [karlogonzales/ministocks-390#43]
## Description
The user should be able to choose a stock data for the **new scrollable widget view**, similar to the other available widget views. 

To do this, the user will access a menu where it will be possible to search for a certain stock to be added to the list of stocks.

*There is currently no menu for this widget, therefore no search function or add stock function. Widget display stub data, it needs to be able to display actual data*

## Tasks Breakdown
- [x] Connect data to the list on the scrollable widget #39 
- [x] Have a menu set up for this new scrollable widget view #44
- [x] Connect data to the search function of the menu #45
- [x] Add stocks to list from the menu #46 

## Comments
- May have to explore the idea of creating our own data provider for the widget if reusing the current code is not compatible with the widget.listview feature currently implemented on the new scrollable widget.
- may have to implement our own menu for the new widget for the same reason as mentioned above.
- Widget may only use the data access implemented from last sprint (cryptocurrency only).
